### ISSUE TITLE
Bliss 1.9 Broken with latest Discord update

### ISSUE THREAD

**Issue by Skyyblaze** [reeseovine/discord-stuff#4]
Ever since a Discord update a few days ago Bliss version 1.9 has some visual defects, mainly the Quick Switcher which lacks any background whatsoever. Is Bliss as a theme still maintained in any form?

**Comment by reeseovine** [comment]
it's not maintained anymore unfortunately. i use discord in the browser now and don't have the energy to keep up every time they change the class names.

you are more than welcome to fork it and continue maintaining it yourself! i can make a note in the readme here as well.
